contracts/src/agreements/test/ActiveAgreementRegistryTest.sol, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/bpm-model/test/ProcessDefinitionTest.sol, contracts/src/bpm-model/test/ProcessModelRepositoryTest.sol, contracts/src/bpm-model/test/ProcessModelTest.sol, contracts/src/bpm-runtime/test/ApplicationRegistryTest.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/bpm-runtime/test/ServiceUpgradeabilityTest.sol, contracts/src/commons-standards/test/ERC165Test.sol, contracts/src/commons-utils/TypeUtilsAPI.sol, contracts/src/commons-utils/TypeUtilsImpl.sol, contracts/src/commons-utils/test/TypeUtilsTest.sol, contracts/src/test-agreements.yaml, contracts/src/test-bpm-model.yaml, contracts/src/test-bpm-runtime.yaml, contracts/src/test-commons-standards.yaml, contracts/src/test-commons-utils.yaml
We've had different approaches to unit testing over time. This PR consolidates all test returns under the simple approach of returning a string from each test function, because the return of uint values as error codes has lost most of its benefit since switching more and more to revert/require with reasons.
Also, some commented out functions in TypeUtilsAPI were removed and the implementation of `bytes32ToString` was moved there from multiple tests.
=> Consolidating solidity unit test returns

api/controllers/contracts-controller.js, api/sqlsol/BpmService.json, contracts/src/agreements/AgreementsAPI.sol, contracts/src/agreements/test/ActiveAgreementRegistryTest.sol, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/bpm-model/test/ProcessDefinitionTest.sol, contracts/src/bpm-model/test/ProcessModelTest.sol, contracts/src/bpm-runtime/BpmRuntimeLib.sol, contracts/src/bpm-runtime/BpmService.sol, contracts/src/bpm-runtime/DefaultBpmService.sol, contracts/src/bpm-runtime/test/ApplicationRegistryTest.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/bpm-runtime/test/ServiceUpgradeabilityTest.sol, contracts/src/commons-auth/DefaultOrganization.sol, contracts/src/commons-auth/DefaultParticipantsManager.sol, contracts/src/commons-auth/Organization.sol, contracts/src/commons-auth/ParticipantsManager.sol, contracts/src/commons-auth/test/ParticipantsManagerTest.sol, contracts/src/commons-standards/test/ERC165Test.sol, contracts/src/test-agreements.yaml, contracts/src/test-commons-auth.yaml
This PR completes AN-553, AN-554, AN-555.
A default department is now added to each organization automatically which serves as a catch-all for "unassigned" tasks, for example. The organization-level authorization has been refactored and is now represented by using a department scope that is the hash (keccak256) of the organization's address.
The agreement's sign() and cancel() functions now correctly respect department scope as well by using a scope set to the the reserved AGREEMENT_PARTIES constant.
The address scopes of process instances are now exposed in SQLsol in a new table PROCESS_INSTANCE_ADDRESS_SCOPES.
Lastly, this PR fixes the error string returns of multiple test contracts that were lost in a prior commit.
=> Default department in organizations as catch-all

api/controllers/contracts-controller.js, api/lib/bpmn-parser.js, contracts/src/bpm-model/BpmModelLib.sol, contracts/src/build-test-commons-collections.yaml, contracts/src/commons-collections/AbstractAddressScopes.sol, contracts/src/commons-collections/DataStorageUtils.sol, contracts/src/commons-collections/test/DataStorageUtilsTest.sol, contracts/src/test-commons-collections.yaml
This PR fixes a bug where the placeholder `PROCESS_INSTANCE` was not removed as a dataStorageId prior to setting transition conditions in the smart contracts. An empty string needs to be passed since the ProcessInstance is the top DataStorage container for data resolution.
Additionally, the function DataStorageUtils.resolveDataLocation was changed to REVERT if for whatever reason a DataStorage address cannot be determined. This guarantees to consuming code that the function always returns a location that is non-zero address.
=> Fix exception when using PROCESS_INSTANCE fields for transition conditions

api/controllers/agreements-controller.js, api/controllers/contracts-controller.js, api/test/api/web-api-bpm-test.js, api/test/data/Execution-NoAction.bpmn, api/test/data/Formation-Tenant-XOR-Gateway.bpmn, contracts/src/bpm-model/DefaultProcessDefinition.sol, contracts/src/bpm-model/ProcessDefinition.sol, contracts/src/bpm-model/test/ProcessDefinitionTest.sol, contracts/src/bpm-runtime/BpmRuntimeLib.sol, contracts/src/bpm-runtime/DefaultProcessInstance.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/commons-collections/test/DataStorageTest.sol, contracts/src/test-bpm-runtime.yaml
This is a fix for uint conditions on XOR gateways seemingly not working. Integers were set in the smart contracts that differed from the intended ones due to burrow.js conversions triggered by blackstone sending string values. Blackstone now converts the value appropriately before calling the smart contracts.
This PR also includes support for successive gateways such that no "pass-thru" (NONE) activity is needed anymore between two gateways.
=> Bugfix: transition conditions for uint values not working

contracts/src/agreements/DefaultActiveAgreementRegistry.sol, contracts/src/bpm-runtime/DefaultBpmService.sol, contracts/src/commons-auth/DefaultUserAccount.sol, contracts/src/commons-management/DefaultContractManager.sol, contracts/src/commons-management/DefaultDoug.sol, contracts/src/commons-management/test/ContractManagerTest.sol, contracts/src/commons-management/test/DougTest.sol, contracts/src/commons-management/test/TestService.sol
This PR enhances certain services that are registered in DOUG's ContractManager in order to listen for changes to contract dependencies and removes them from the list of listeners after an upgrade.
=> Remove contract change listeners on upgrade

api/common/controller-dependencies.js, api/common/passport.js, api/controllers/agreements-controller.js, api/controllers/contracts-controller.js, api/controllers/participants-controller.js, api/controllers/postgres-query-helper.js, api/data/seeds.js, api/migrations/20181106211133-change-username-column-size.js, api/scripts/migrateUsers.js, api/sqlsol/ParticipantsManager.json, api/test/api/web-api-bpm-test.js, api/test/controllers/contracts-test.js, api/test/controllers/form-exec-usertask-test.js, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/commons-auth/DefaultEcosystem.sol, contracts/src/commons-auth/DefaultParticipantsManager.sol, contracts/src/commons-auth/DefaultUserAccount.sol, contracts/src/commons-auth/Ecosystem.sol, contracts/src/commons-auth/Governance.sol, contracts/src/commons-auth/ParticipantsManager.sol, contracts/src/commons-auth/ParticipantsManagerDb.sol, contracts/src/commons-auth/UserAccount.sol, contracts/src/commons-auth/test/ParticipantsManagerTest.sol, contracts/src/commons-auth/test/UserAccountTest.sol, contracts/src/deploy-module-Ecosystem.yaml
Changes:
- User ids are now SHA256 hashed in API layer before sending to chain
- Chain only stores hashed ids for privacy
- All auth functions hash user submitted ids before validating with chain
- UserIds are now stored in a Address-to-UserId hash in the Ecosystem contract
- To get user account address, the API must submit the UserId and ecosystem address where the Id is registered
- Username field in the postgres `users` table has been updated to varchar(255) for storing longer ids/emails
=> [AN-576] : [UserIdHasing] - User id is now pre-hashed in api

.circleci/config.yml, Dockerfile, Makefile, api/config/settings.toml, api/package-lock.json, contracts/Dockerfile, docker-compose.yml, test/chain/burrow.toml, test/clean, test/preflight, test/test_api.sh, test/test_bundle.sh, test/test_contracts.sh
This:
- Drops the use of monax/build for anything
- Introduces a Dockerfile that builds a test service called 'api' through which most command are run (instead of 'chain')
- Makes chain a separate service that just runs burrow (it could use the vanilla Burrow image - would look cleaner but would mean two places to update docker image.
- Runs the exact same docker-compose based tests (`make test`) in CI as in dev
=> Upgrade to Burrow 0.23.1 and give chain its own container and image

api/controllers/contracts-controller.js, contracts/build_contracts, contracts/src/agreements/ActiveAgreementRegistry.sol, contracts/src/agreements/DefaultActiveAgreementRegistry.sol, contracts/src/agreements/DefaultArchetypeRegistry.sol, contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/agreements/test/ArchetypeRegistryTest.sol, contracts/src/test-agreements.yaml
The PR adds changes to the DefaultArchetypeRegistry to not require formation and execution process definitions when creating archetypes. Also, DefaultActiveAgreementRegistry was changed to deal with agreements from archetypes with varying combinations of formation / execution workflows (or their lack).
=> Feature AN-544: Make agreement processes optional

docker-compose.yml
Gives us `target` keyword and should work with our machine version:
> circleci/classic:201808-01 – docker 18.06.0-ce, docker-compose 1.22.0
=> Use docker-compose file version 3.4

docker-compose.yml
=> Bump Vent to version that only consumes EVM log events and filters

api/controllers/contracts-controller.js, contracts/src/bpm-model/DefaultProcessModelRepository.sol
- Changing the error thrown on a duplicate modelId to be something akin to bad request rather than invalid state
- Updating error handling in JS side to accommodate ErrorsLib error code instead of previously returned BaseErrors error code
=> Changing model deploy error code

api/common/controller-dependencies.js, api/controllers/agreements-controller.js, api/controllers/bpm-controller.js, api/controllers/participants-controller.js, api/controllers/postgres-query-helper.js
- Send account details with agreement parameters (ie. if user/org type parameter, include their username/org name)
- Add new `getParticipantNames` function which replaces 2 separate `getOrganizationNames` and `getUserIds` functions.
- Remove unused `format` cases and calls
- Remove unused `getAgreementParties` function
- Add username/org name of activity instance's `completedBy` account to activity instance detailsAdd account details to agreement parameters
- Add username/org name of activity instance `completedBy` and `performer` accounts to queries
=> MP-683-add-account-details-to-parameters

api/controllers/contracts-controller.js, api/package-lock.json, api/package.json, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/build-test-commons-management.yaml, contracts/src/commons-auth/DefaultUserAccount.sol, contracts/src/commons-auth/UserAccount.sol, contracts/src/commons-auth/test/UserAccountTest.sol, contracts/src/commons-management/AbstractDelegateProxy.sol, contracts/src/commons-management/test/DelegateProxyTest.sol, contracts/src/commons-management/test/DougProxyTest.sol, contracts/src/test-commons-management.yaml, test/test_contracts.sh
Revert reason was not re-thrown in DefaultUserAccount when it originated in the forward target contract. Breaking change: the .forwardCall function signature now only returns the payload and not a bool to signal success. Added a new test commons-management/DelegateProxyTest.sol.
=> Implemented the DefaultUserAccount re-throwing a revert reason

Makefile, contracts/deploy_contracts
Upstream runs these targets in independent runs of Make and so
deduplication does not happen there. Better to separate.
=> Decouple build and deploy

README.md, api/controllers/agreements-controller.js, api/controllers/contracts-controller.js, api/sqlsol/Tables.json, contracts/src/agreements/Archetype.sol, contracts/src/agreements/ArchetypeRegistry.sol, contracts/src/agreements/DefaultArchetype.sol, contracts/src/agreements/DefaultArchetypeRegistry.sol, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/src/agreements/test/ArchetypeRegistryTest.sol, contracts/src/documents-commons/Documents.sol
The bytes32 key are now generated in the contract rather than passed in. This avoids someone using a filename as key and accidentally revealing information about the file's contents.
=> Refactored the archetype documents to be stored in a Bytes32StringMap

contracts/src/agreements/ActiveAgreement.sol, contracts/src/agreements/Archetype.sol, contracts/src/agreements/DefaultActiveAgreement.sol, contracts/src/agreements/DefaultArchetype.sol
Original events LogArchetypeCreation and LogAgreementCreation were restored to allow event processing layers to process old events from chain. Latest event definitions were appended with v1_0_0.
=> Restore original event definitions and versionize new ones

api/common/VentHelper.js
Listener was added with ".once" instead of ".on" which might result in skipped notifications. Changed it to ".on" and removed the listener once target height is reached.
=> Updated vent-helper height event listener

Dockerfile, test/chain/burrow.toml
Note that this release makes the tendermint option CreateEmptyBlocks
work, so that is off now.
Signed-off-by: Sean Young <sean.young@monax.io>
=> burrow 0.26.0

api/common/VentHelper.js
When client is disconnected, it will create a new client and resume listening for height notifications.
=> Made VentHelper pg connection more resilient

docker-compose.yml
This burrow version removes varchar(100) limits on _vent_log columns.
=> Updating docker-compose to use burrow 0.28.1 for vent

contracts/src/commons-auth/DefaultEcosystem.sol
=> On user-id migration the old userid:address mapping is now removed

api/package.json
appears to be pinning to version we used to use not protecting from any specific incompatibility. Given
it is a library I think it is better not to contrain at this level. Could be persuaded otherwise on this. But trying to get CI working with yarn which rejects based on this.
=> Remove node engines from package json

.github/workflows/release.yaml, CHANGELOG.md
Also don't build on every commit on master. If we are going to build
every master commit there is no point in release. So assuming we still
want versions use tags for major builds
=> Changelog for 2.0.0

CHANGELOG.md, src/agreements/Completables.sol
Since we allow intervalID to be arbitrary (e.g. UUID) bytes.
=> Remove empty-string check on intervalID
