agreements-network/blackstone

.circleci/config.yml
=> first run at circle ci

.circleci/config.yml, contracts/Dockerfile
=> upgrades to circle ci config and contracts/dockerfile

api/routes/agreements-api.js
=> fixup docs so theyll build

README.md
=> bring out BPM on top of readme

.circleci/config.yml
=> update chain info from ci

.circleci/config.yml
=> update ci info script

.circleci/config.yml
=> uncomment deps

contracts/src/bpm-runtime/Application.sol, contracts/src/bpm-runtime/ProcessStateChangeEmitter.sol, contracts/src/bpm-runtime/WorkflowProxy.sol, contracts/src/commons-base/AbstractNamedElement.sol, contracts/src/commons-collections/AddressScopes.sol, contracts/src/commons-collections/DataStorage.sol, contracts/src/commons-management/Migratable.sol
=> Converted interfaces to contracts to remove compiler warnings

api/controllers/agreements-controller.js, api/controllers/contracts-controller.js
Set scope for agreement parameter if given.
=> AN-550/Detect scope on agreement parameters

api/common/monax-sqlsol.js, api/controllers/contracts-controller.js, api/routes/agreements-api.js, api/sqlsol/Tables.spec, contracts/src/agreements/ActiveAgreement.sol, contracts/src/agreements/ActiveAgreementRegistry.sol, contracts/src/agreements/Archetype.sol, contracts/src/agreements/ArchetypeRegistry.sol, contracts/src/agreements/DefaultActiveAgreement.sol, contracts/src/agreements/DefaultActiveAgreementRegistry.sol, contracts/src/agreements/DefaultArchetype.sol, contracts/src/agreements/DefaultArchetypeRegistry.sol, docker-compose.yml
Added new Postges tables for Archetypes, Agreements and their children
Added Solidity events for Vent consumption for the above
=> Vent Integration

api/controllers/contracts-controller.js
=> Add back string to hex conversion for country codes and param names

api/controllers/agreements-controller.js, api/controllers/sqlsol-query-helper.js, api/routes/agreements-api.js
Add documents, parameter type, and process definitions to GET /agreements/:address response
=> AN-512 Harmonize Agreement and Archetype object

api/controllers/bpm-controller.js
Removed chaining of condition-creation promises onto transition-creation promises.
Ensures that all transitions are created before conditions are created, and that all conditions are created before validating the process.
=> Separate promises for transition and condition creation

api/common/controller-dependencies.js, api/controllers/agreements-controller.js, api/controllers/participants-controller.js, api/controllers/sqlsol-query-helper.js, api/migrations/20181015143206-addExternalUserToUsers.js
=> Accept email address for user/org/signatories

api/common/aa-web-api.js, api/common/passport.js, api/sqlsol/Tables.spec, api/test/api/web-api-bpm-test.js, contracts/src/bpm-model/DefaultProcessDefinition.sol, contracts/src/bpm-model/DefaultProcessModel.sol, contracts/src/bpm-model/ProcessDefinition.sol, contracts/src/bpm-model/ProcessModel.sol, contracts/src/bpm-runtime/BpmRuntimeLib.sol, contracts/src/bpm-runtime/BpmService.sol, contracts/src/bpm-runtime/DefaultBpmService.sol
=> Added vent events for processes and activities

api/controllers/agreements-controller.js, api/test/api/web-api-bpm-test.js
Updated controller to handle case where same email address is entered for multiple parameters.
Added tests.
=> Updates and tests for external users in agreement parameters

api/controllers/postgres-cache-helper.js
=> hotfix for activity names

contracts/src/bpm-runtime/BpmRuntimeLib.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/test-bpm-runtime.yaml
Identified and fixed missing activity node reset of completed instances from prior execution.
=> Fix for looping bug in the process graph

api/schemas/agreement.js, api/schemas/archetype.js
=> Remove title length restriction from archetype and agreement schema

api/common/aa-web-api.js
Add custom endpoints first to allow overwriting.
=> Move addition of custom endpoints

contracts/abi.csv
=> add BpmRuntimeLib to abis to test if this fixes vents problem

.circleci/config.yml, test/test_api.sh
=> package and run vent as background process for tests

api/app.js
=> Accept callback for adding/overwriting global variables

api/controllers/contracts-controller.js, contracts/src/commons-auth/DefaultEcosystem.sol, contracts/src/commons-auth/DefaultParticipantsManager.sol, contracts/src/commons-auth/ParticipantsManager.sol, contracts/src/commons-auth/test/ParticipantsManagerTest.sol
=> Removed unused functions in ParticipantsManager

.circleci/config.yml
=> change ci deploy job

api/controllers/contracts-controller.js
=> Fixed missing .factory when encoding function payloads for the BpmService

api/app.js, api/common/aa-web-api.js, api/common/controller-dependencies.js, api/common/passport.js, api/common/postgres-db.js, api/config/settings.toml, api/controllers/agreements-controller.js, api/controllers/participants-auth-controller.js, api/controllers/participants-controller.js, api/controllers/postgres-cache-helper.js, api/controllers/postgres-query-helper.js, api/data/seeds.js, api/database.json, api/scripts/migrateUsers.js, api/test/api/web-api-bpm-test.js, api/test/api/web-api-test.js, test/test_api.sh
=> Split db connections into appDb and chainDb for respective queries

api/common/controller-dependencies.js
Should query organizations table in app db
=> Fix db pool for query

api/app.js, api/database.json
=> removed db schema from connection string

.circleci/config.yml, Dockerfile, Makefile, contracts/deploy_contracts, docker-compose.yml, scripts/update_info.sh, test/chain/burrow.toml, test/clean, test/test_contracts.sh
This PR makes us run as local user that avoids npm and other files being written as root which makes development and dependencies easier. We can also avoid cleaning up through a docker container but I've left as it is for now to check this works across other machines.
=> Run as local user

scripts/update_info.sh
=> change script env

api/controllers/postgres-cache-helper.js, api/controllers/postgres-query-helper.js
Minor updates to postgres-cache-helper
=> Removed postgres event handler for activity instance state change

LICENSE
which includes updates to application rule
=> update license to parity v4.0.0

CHANGELOG.md
=> Added CHANGELOG.md with relevant changes for version 0.5.0 release.

.circleci/config.yml, Makefile, api/package-lock.json, api/package.json, contracts/Dockerfile, contracts/build_contracts, contracts/deploy_contracts, docker-compose.yml, test/clean, test/preflight, test/test_api.sh, test/test_contracts.sh
Centralises contract build logic and other tweaks so that blackstone's build/test/deploy framework can be used downstream more easily.
=> Restructure build/deploy scripts

Dockerfile, scripts/ensure_user.sh
=> Ensure container user exists

scripts/update_info.sh
=> change abi cp dir

Dockerfile, Makefile, scripts/ensure_user.sh
=> Set workdir to homedir and clean up dependencies

scripts/update_info.sh, test/preflight
=> Set update_info to correct workspace

Makefile
=> Derp don't cleanup bins

docker-compose.yml
=> Taggity tag for vent

api/controllers/postgres-query-helper.js
=> hotfix for converting postgres bigint values to JS integer

api/migrations/20181106211133-change-username-column-size.js
=> Fixed incorrect column type in users migration

CHANGELOG.md
=> Updated CHANGELOG for 0.5.2 release

api/schemas/user.js
=> Change max length of username

api/controllers/contracts-controller.js
=> Exposed ecosystem registration functions from contracts

api/controllers/contracts-controller.js, api/sqlsol/Tables.spec
=> Added marmot game vent table

Makefile, docker-compose.yml
=> fixup docker-compose ports

api/common/controller-dependencies.js, api/controllers/agreements-controller.js
Return empty array if no docs and check for nonexistent formation/execution process
=> Handle empty docs and processes in GET archetype

docker-compose.yml
=> version bump vent in docker-compose file

Dockerfile, contracts/Dockerfile
=> update to 0.23.3

api/controllers/contracts-controller.js, api/package-lock.json, api/test/api/web-api-bpm-test.js
Fixed a bug in contracts-controller to use the completeActivityWithData... function on the ProcessInstance to complete and set data in a single transaction. Adapted a test in web-api-bpm-test.js to cover this code path.
=> Fixed a bug in contracts-controller when completing an ActivityInstance with data

api/controllers/bpm-controller.js
=> MP-337 Add performer name to activity instance details

api/controllers/contracts-controller.js, api/controllers/participants-controller.js, api/schemas/user.js, api/test/api/web-api-agreements-test.js
=> Allow external users to register for account

api/controllers/bpm-controller.js, api/controllers/postgres-query-helper.js, api/routes/bpm-api.js
=> Updated GET /bpm/process-definitions route to add option query params

api/sqlsol/Tables.spec, api/test/api/web-api-agreements-test.js, api/test/api/web-api-bpm-test.js, api/test/api/web-api-test.js, contracts/src/bpm-model/DefaultProcessDefinition.sol, contracts/src/bpm-model/ProcessDefinition.sol
Adds the second table DATA_MAPPINGS
Fixes #132 
=> Added DATA_MAPPINGS table

contracts/abi.csv
=> Added DataTypesAccess to csv

contracts/abi.csv
=> Adding Static data and BpmRuntimeLib binaries for vent table spec

api/app.js, api/common/aa-web-api.js, api/common/middleware.js, api/controllers/contracts-controller.js, api/package-lock.json, api/routes/agreements-api.js, api/routes/bpm-api.js, api/routes/hoard-api.js, api/routes/participants-api.js, api/routes/static-data-api.js
Adds the ability to push your custom passport auth strategies and middleware to blackstone
=> Custom middleware

api/common/controller-dependencies.js, api/schemas/archetype.js
=> Add support for new parameter types 11, 12

api/package-lock.json, api/package.json
=> reverting helmet version in api package.json

CHANGELOG.md
=> Added CHANGELOG entry for release 0.6.1

api/app.js, api/common/aa-web-api.js, api/common/controller-dependencies.js, api/common/passport.js, api/common/postgres-db.js, api/config/settings.toml, api/controllers/agreements-controller.js, api/controllers/data-storage-controller.js, api/controllers/participants-auth-controller.js, api/controllers/participants-controller.js, api/controllers/postgres-cache-helper.js, api/controllers/postgres-query-helper.js, api/data/seeds.js, api/scripts/migrateUsers.js, api/test/api/api-helper.js, api/test/api/web-api-agreements-test.js, api/test/api/web-api-bpm-test.js, api/test/controllers/contracts-test.js, docker-compose.yml
=> Updated db connections with schema

api/controllers/participants-controller.js, api/controllers/postgres-query-helper.js
=> Prepending http/https to redirect url after user activation

api/controllers/participants-auth-controller.js
Add logging
Release db client
Wrap endpoint in `asyncMiddleware`
Fix delete request code query
=> Update password change request endpoint

api/migrations/20190208204024-create-customers-tables.js
=> Migration script path fix

docker-compose.yml
=> turn off block and tx propagation on tests

contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/test-agreements.yaml
=> Moved the creation of some services out of the ActiveAgreementWorkflowTest

api/initdb.js, api/migrations/scripts/create-customers-tables.sql
=> Made customers db script idempotent

api/sqlsol/Tables.spec, contracts/src/agreements/test/ActiveAgreementRegistryTest.sol, contracts/src/agreements/test/ActiveAgreementWorkflowTest.sol, contracts/src/agreements/test/ArchetypeRegistryTest.sol, contracts/src/bpm-model/test/ProcessModelRepositoryTest.sol, contracts/src/bpm-model/test/ProcessModelTest.sol, contracts/src/bpm-runtime/test/BpmServiceTest.sol, contracts/src/commons-auth/test/EcosystemTest.sol, contracts/src/commons-auth/test/ParticipantsManagerTest.sol, contracts/src/commons-management/DOUG.sol, contracts/src/commons-management/DefaultArtifactsRegistry.sol, contracts/src/commons-management/DefaultDoug.sol, contracts/src/commons-management/TestDoug.sol, contracts/src/commons-management/test/ArtifactsRegistryTest.sol, contracts/src/commons-management/test/DougProxyTest.sol, contracts/src/commons-management/test/DougTest.sol, contracts/src/commons-management/test/ObjectProxyTest.sol, contracts/src/test-bpm-runtime.yaml, contracts/src/test-commons-management.yaml
This PR adds the functions deployVersion, registerVersion, and lookupVersion to the DOUG interface and DefaultDoug implementation as well as increases DOUG test coverage. Additionally, some improvements that decrease the binary footprint of the BpmServiceTest.
=> Feature/MP-673 DOUG enhancements

api/common/controller-dependencies.js, api/controllers/participants-auth-controller.js, api/controllers/participants-controller.js
=> Fixed password change email link

api/controllers/contracts-controller.js, api/controllers/data-storage-controller.js
Added comments for other bytes32 ids where this conversion is needed - further testing required
=> Converting human readable departmentIds to hex before sending tx payload

api/controllers/participants-controller.js
=> Adding a redirect on bad user activation request

api/controllers/contracts-controller.js, contracts/src/commons-collections/DataStorageUtils.sol
This PR fixes a bug which caused boolean-based transition conditions using a "= false" condition to be recorded as "= true".
=> Bugfix for boolean-based gateway decisions

api/controllers/bpm-controller.js
=> Handle aborted state in GET activity instance

Dockerfile
Signed-off-by: Sean Young <sean.young@monax.io>
=> Upgrade to burrow 0.24.1

api/common/controller-dependencies.js, api/controllers/contracts-controller.js, api/package-lock.json, api/package.json, api/test/api/web-api-test.js
Fixed hex-to-string conversion tests
=> Upgraded burrow-js to 0.24.3

Dockerfile
=> bump burrow version

contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/src/agreements/test/ArchetypeRegistryTest.sol
=> re-enabled commented tests in ArchetypeRegistryTest

LICENSE
=> upgrade parity license to v6.0.0

api/common/controller-dependencies.js
=> Format empty process definition address values for agreement

api/controllers/bpm-controller.js
=> Export addDataDefinitionsToModel

api/controllers/agreements-controller.js
=> Check service task data mappings for public parameters

api/controllers/postgres-query-helper.js
=> Fix query for model author display name

api/common/aa-web-api.js, api/controllers/agreements-controller.js, api/controllers/bpm-controller.js, api/controllers/contracts-controller.js, api/controllers/participants-controller.js, api/package-lock.json
Updated the agreement and archetype creation functions to return the respective addresses after creation in res.data such that downstream functions can perform other processing with the addresses. Updated contracts-controller boomify function to handle burrow-js errors.
=> Agreement and Archetype creation

api/controllers/contracts-controller.js
=> Export setToNameRegistry function from contracts controller

api/package-lock.json, api/sqlsol/Tables.json, api/test/constants.js, contracts/src/agreements/ActiveAgreement.sol, contracts/src/agreements/DefaultActiveAgreement.sol, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/test_contracts, contracts/upgrades/ActiveAgreement.yaml, docs/smart_contracts.md, test/chain/burrow.toml
Don't merge, this still needs a upgrade .yaml file for the ActiveAgreement contract.
=> Flexible document references in ActiveAgreement

contracts/src/agreements/ActiveAgreementRegistry.sol, contracts/src/agreements/DefaultActiveAgreementRegistry.sol, contracts/upgrades/ActiveAgreementRegistry.yaml
Added upgrade yaml file for ActiveAgreementsRegistry.
=> Added missing setSignatureLogReference function in ActiveAgreementRegistry

api/controllers/bpm-controller.js
We can probably be smarter about this and check both...
=> change signer ip request header

api/controllers/bpm-controller.js
=> lowercase x header

api/controllers/agreements-controller.js
=> Store agreement parameters in response data obj

api/controllers/participants-auth-controller.js
=> Fix schemas for password reset queries

.gitignore, api/common/aa-web-api.js, api/common/gracefulShutdown.js, api/common/postgres-db.js, api/controllers/participants-auth-controller.js, api/controllers/participants-controller.js, api/controllers/postgres-query-helper.js, api/scripts/migrateUsers.js, api/test/api/api-helper.js, api/test/api/web-api-bpm-test.js, api/test/controllers/contracts-test.js
=> Refactored db pool export, and added gracefulShutdown

api/controllers/agreements-controller.js, api/test/api/web-api-agreements-test.js
=> Remove check for max attachments length

api/common/controller-dependencies.js, api/controllers/agreements-controller.js
=> Validate all agreement params, update param formatting

api/controllers/postgres-query-helper.js
=> remove misplaced quote

api/controllers/postgres-query-helper.js
Fixes query for archetypes in package.
=> Add missing schema to query

api/controllers/contracts-controller.js
=> Convert scope context to hex

.circleci/config.yml, Makefile, api/routes/agreement-collections-api.js, api/routes/agreements-api.js, api/routes/archetype-packages-api.js, api/routes/archetypes-api.js, api/routes/bpm-models-api.js, api/routes/bpm-runtime-api.js, api/routes/hoard-api.js, api/routes/organizations-api.js, api/routes/static-data-api.js, api/routes/users-api.js, swagger.json, swaggerDef.js
It's gonna be rough around the edges because most of the replacements were done with an automatic parsing tool. In a similar vein, not all methods/variables were documented so I've done my best to fill in the gaps.
Run `make swaggerize` to regen.
You'll need the swagger-jsdoc tool (`npm install swagger-jsdoc -g`) and the go-swagger binary; follow the guide [here](https://goswagger.io/install.html).
To view the docs: `swagger serve swagger.json`
=> swaggerize the AN

.circleci/config.yml
=> CircleCI you stupid

api/common/logger.js
=> Added log level to json output

.gitattributes, .gitignore
=> Adding .gitattributes file for sol syntax highlighting on github

contracts/src/agreements/ActiveAgreement.sol
=> Fixed primary key for LogAgreementOwnerUpdate event

api/common/VentHelper.js
=> Setting log-level trace to high water log

api/package-lock.json, api/package.json, docker-compose.yml
=> update hoard version

Dockerfile, test/chain/burrow.toml
=> Upgraded Burrow version to 0.26.1

api/controllers/contracts-controller.js, contracts/src/agreements/ArchetypeRegistry.sol, contracts/src/agreements/DefaultActiveAgreement.sol, contracts/src/agreements/DefaultArchetype.sol, contracts/src/agreements/DefaultArchetypeRegistry.sol, contracts/src/agreements/test/ArchetypeRegistryTest.sol, contracts/src/build-test-commons-auth.yaml, contracts/src/commons-auth/AbstractPermissioned.sol, contracts/src/commons-auth/test/PermissionedTest.sol, contracts/src/commons-collections/AddressScopes.sol, contracts/src/commons-collections/Collections.sol, contracts/src/deploy-module-Agreements.yaml, contracts/src/test-agreements.yaml, contracts/src/test-commons-auth.yaml, contracts/upgrades/Archetype.yaml, contracts/upgrades/ArchetypeRegistry.yaml
=> Authorize archetype owner to activate/deactivate

api/controllers/agreements-controller.js, api/controllers/participants-controller.js, api/routes/agreements-api.js, api/schemas/agreement.js
- Export create agreement, create organization, and add organization members functions
- Update agreements joi schema
=> Additional controller exports, agreements joi schema updates

api/package.json
=> Adding explicit grpc/proto-loader dep to avoid npm errors

api/controllers/postgres-query-helper.js
Display user first+last name for user/org params and signatories if available
=> feature/MP-912 First+Last name for user/org parameters and signatories

api/controllers/postgres-query-helper.js
=> Add external user flag to query return

api/controllers/agreements-controller.js, api/schemas/archetype.js, api/test/api/web-api-agreements-test.js, api/test/api/web-api-bpm-test.js, api/test/data/AN-TestTemplate-FE.bpmn, api/test/data/AN-TestTemplate-sale.bpmn, api/test/data/data-mapping-execution.bpmn
- Require all parameters used in model to be added to archetype (check param name + type)
- Use Joi schema for price and governing agreement format
=> Usability/MP-481 Require all parameters used in model to be present in archetype

Dockerfile, api/sqlsol/EventLog.json, docker-compose.yml
+ Extended event_log table to include other event types
=> Update burrow version for vent to 0.28.0

docker-compose.yml
=> Updating burrow to 0.28.2

api/common/constants.js, api/controllers/agreements-controller.js, api/controllers/bpm-controller.js, api/controllers/contracts-controller.js, api/controllers/data-storage-controller.js, api/controllers/postgres-query-helper.js, api/controllers/static-data-controller.js, api/lib/bpmn-parser.js, api/migrations/20190903122719-createParametersTable.js, api/package-lock.json, api/package.json, api/schemas/archetype.js, api/test/data/parser-timer.bpmn, api/test/parser/parser-test.js
Add parser and controller functions for handling timers and add duration parameter type
=> API changes for timers and duration parameter

api/controllers/contracts-controller.js
=> Minor change in getFromNameRegistry log statement

Dockerfile
=> Changed SOLC_VERSION in Dockerfile to 0.5.12

contracts/src/bpm-runtime/test/BpmServiceTest.sol
=> Merge latest update from MP-877

api/package.json, docker-compose.yml
=> upgrade to hoard v6

api/controllers/contracts-controller.js, api/test/controllers/user-migration-tests.js
=> Replaced refs to uuid with userid in api

api/package-lock.json
=> Update package-lock for hoard v6

api/controllers/contracts-controller.js
Exposes the `isSignedBy` function on the `AbstractActiveAgreement` smart contract in controller-contracts
=> Check agreement sign

contracts/src/commons-auth/Ecosystem_v1_0_1.sol
=> Updated solc version for Ecosystem v101

contracts/src/agreements/ActiveAgreementRegistry.sol
=> import object factory in ActiveAgreementRegistry

api/contracts.js
=> fixes getFromNameRegistry for burrow 0.29.5

api/contracts.js, contracts/src/agreements/AbstractActiveAgreement_v1_0_1.sol, contracts/src/agreements/ActiveAgreement_v1_0_1.sol, contracts/src/agreements/DefaultActiveAgreement.sol, contracts/src/agreements/test/ActiveAgreementTest.sol, contracts/upgrades/ActiveAgreement.yaml
=> Add functions to set private parameters file reference

contracts/src/bpm-model/ProcessDefinition.sol, contracts/src/bpm-runtime/BpmRuntime.sol, contracts/src/bpm-runtime/BpmRuntimeLib.sol, contracts/src/bpm-runtime/DefaultProcessInstance.sol, contracts/src/bpm-runtime/ProcessInstance.sol
This needs:
- comments updating
- execution on boundary event firing
- tests
=> Add boundary events runtime processing

package.json, src/index.ts
=> expose client from index

Makefile, abi.csv, package.json, yarn.lock
=> better build in make, with updated abi.csv

package.json, src/deploy.ts, src/lib/constants.ts
=> deploy should register libraries

src/lib/contracts.ts
=> Convert hex values to buffers with DecodeHex instead of BytesFromString

src/commons-math/deploy.ts
Wait for application registration before access point registration
=> Fix math-commons deploy

src/bpm-oracles/deploy.ts, src/commons-math/deploy.ts
=> Wait for application registration for deadline/wait oracles too

CHANGELOG.md, package.json
=> Release notes for v1.0.0

package.json
=> Remove usage of push/pop-d

.github/workflows/release.yaml
=> Fetch tags for npm version

.github/workflows/release.yaml
=> Upgrade from actions/checkout@v1 to actions/checkout@v2

.github/workflows/release.yaml
=> Work aroudn multiple git-related tool stupidities

.github/workflows/release.yaml
=> Fix publish steps

.github/workflows/release.yaml
=> Install burrow for release job

.github/workflows/release.yaml
=> Add Setup Go step to release

.github/workflows/release.yaml
=> Install solc with brew

src/lib/contracts.ts
=> Fix conversion of string to boolean for transition condition

.github/workflows/release.yaml, .github/workflows/test.yaml, .gitignore, DeveloperGuide.md, Makefile, package.json, scripts/build_contracts, src/build.ts, yarn.lock
=> Emit ABIs from JS compile

.github/workflows/release.yaml
=> Fix yarn version set

src/agreements/AbstractRenewable.sol, src/agreements/Renewable.sol, src/agreements/test/ActiveAgreementTest.sol, src/test-agreements.yaml
=> added renewable tests

src/bpm-runtime/DefaultProcessInstance.sol
Since lair is at least once we should allow for duplicate sends after a
fault
=> Make intermediate timer set and trigger idempotent

CHANGELOG.md
=> Add changelog for 2.1.0

src/lib/contracts.ts
Signed-off-by: Casey Kuhlman <casey.kuhlman@monax.io>
=> allow clients to set the log level

src/deploy.ts
=> Export deployment functions

CHANGELOG.md
=> v5 changelog notes

.github/workflows/release.yaml, CHANGELOG.md, Makefile, docker-compose.yml, package.json, scripts/version.sh, src/lib/manager.ts, src/lib/utils.ts, src/tests/migrations.test.ts, yarn.lock
=> Upgrade Burrow

scripts/version.sh
=> Update version script
